% Auto-generated by railroad/extractor.pl — do not edit by hand.
% EBNF intermediate representation for the railroad diagrams.

:- module(ebnf, [ebnf_rule/2, ebnf_start/1, ebnf_leaf/1, ebnf_order/1]).

ebnf_start(statement).

ebnf_leaf(identifier).
ebnf_leaf(string_literal).
ebnf_leaf(integer_literal).
ebnf_leaf(decimal_literal).

ebnf_order([statement,trailing_semicolon_opt,statement_body,select_chain,transaction_statement,import_statement,export_statement,maint_statement,rename_statement,alter_table_statement,create_index_statement,drop_index_statement,drop_table_statement,insert_statement,delete_statement,update_statement,select_statement,maint_op,cast_type,index_col_list,create_index_modifier,drop_if_exists_opt,insert_source,insert_cols_opt,where_opt,set_clause_list,modifier_list,table_ref_list,column_list,distinct_opt,type_keyword,index_col,value_list,ident_list,predicate_or,set_clause,modifier,table_or_joined,column_or_star,value,predicate_and,set_lhs,order_item_list,group_by_list,table_ref,join_type,column_alias_opt,column_or_star_bare,additive,predicate_atom,order_item,table_name,multiplicative,cmp_op,in_rhs,unary,primary,function_call,case_expr,cast_expr,func_arg_list,func_arg,trim_separator,trim_side,extract_field,case_body,cast_separator,case_else_opt,case_when_list_simple,case_when_list_searched,case_when_list_simple_more,case_when_list_searched_more]).

ebnf_rule(statement, seq([nt(statement_body),nt(trailing_semicolon_opt)])).
ebnf_rule(trailing_semicolon_opt, opt(term(;))).
ebnf_rule(statement_body, choice([nt(update_statement),nt(delete_statement),nt(insert_statement),nt(drop_table_statement),nt(drop_index_statement),nt(create_index_statement),nt(alter_table_statement),nt(rename_statement),nt(maint_statement),nt(export_statement),nt(import_statement),nt(transaction_statement),nt(select_chain)])).
ebnf_rule(select_chain, seq([nt(select_statement),zero_or_more(choice([seq([term('UNION'),term('ALL'),nt(select_statement)]),seq([term('UNION'),nt(select_statement)])]))])).
ebnf_rule(transaction_statement, choice([seq([term('START'),term('TRANSACTION')]),seq([term('COMMIT'),term('WORK')]),term('COMMIT'),seq([term('ROLLBACK'),term('WORK')]),term('ROLLBACK')])).
ebnf_rule(import_statement, seq([term('IMPORT'),term('TABLE'),leaf(identifier),term('FROM'),leaf(identifier)])).
ebnf_rule(export_statement, seq([term('EXPORT'),term('TABLE'),leaf(identifier),term('TO'),leaf(identifier)])).
ebnf_rule(maint_statement, seq([nt(maint_op),term('TABLE'),leaf(identifier)])).
ebnf_rule(rename_statement, seq([term('RENAME'),term('TABLE'),leaf(identifier),term('TO'),leaf(identifier)])).
ebnf_rule(alter_table_statement, seq([term('ALTER'),term('TABLE'),leaf(identifier),term('ADD'),leaf(identifier),nt(cast_type)])).
ebnf_rule(create_index_statement, seq([term('CREATE'),nt(create_index_modifier),term('INDEX'),leaf(identifier),term('ON'),leaf(identifier),term('('),nt(index_col_list),term(')')])).
ebnf_rule(drop_index_statement, choice([seq([term('DROP'),term('INDEX'),leaf(identifier),term('.'),leaf(identifier)]),seq([term('DROP'),term('INDEX'),leaf(identifier)])])).
ebnf_rule(drop_table_statement, seq([term('DROP'),term('TABLE'),nt(drop_if_exists_opt),leaf(identifier)])).
ebnf_rule(insert_statement, seq([term('INSERT'),term('INTO'),leaf(identifier),nt(insert_cols_opt),nt(insert_source)])).
ebnf_rule(delete_statement, seq([term('DELETE'),term('FROM'),leaf(identifier),nt(where_opt)])).
ebnf_rule(update_statement, seq([term('UPDATE'),leaf(identifier),term('SET'),nt(set_clause_list),nt(where_opt)])).
ebnf_rule(select_statement, choice([seq([term('SELECT'),nt(distinct_opt),nt(column_list),term('INTO'),leaf(identifier),term('FROM'),nt(table_ref_list),nt(modifier_list)]),seq([term('SELECT'),nt(distinct_opt),nt(column_list),term('FROM'),nt(table_ref_list),nt(modifier_list)])])).
ebnf_rule(maint_op, choice([term('EMPTY'),term('OPTIMIZE'),term('VERIFY'),term('REPAIR'),term('UPGRADE')])).
ebnf_rule(cast_type, choice([seq([nt(type_keyword),term('('),leaf(integer_literal),term(')')]),nt(type_keyword)])).
ebnf_rule(index_col_list, one_or_more(nt(index_col),term(','))).
ebnf_rule(create_index_modifier, opt(choice([term('UNIQUE'),term('NOCASE')]))).
ebnf_rule(drop_if_exists_opt, opt(seq([term('IF'),term('EXISTS')]))).
ebnf_rule(insert_source, choice([seq([term('VALUES'),term('('),nt(value_list),term(')')]),nt(select_chain)])).
ebnf_rule(insert_cols_opt, opt(seq([term('('),nt(ident_list),term(')')]))).
ebnf_rule(where_opt, opt(seq([term('WHERE'),nt(predicate_or)]))).
ebnf_rule(set_clause_list, one_or_more(nt(set_clause),term(','))).
ebnf_rule(modifier_list, zero_or_more(nt(modifier))).
ebnf_rule(table_ref_list, one_or_more(nt(table_or_joined),term(','))).
ebnf_rule(column_list, one_or_more(nt(column_or_star),term(','))).
ebnf_rule(distinct_opt, opt(choice([term('DISTINCT'),term('ALL')]))).
ebnf_rule(type_keyword, choice([term('VARCHAR'),term('CHAR'),term('INTEGER'),term('SMALLINT'),term('LARGEINT'),term('FLOAT'),term('BOOLEAN'),term('DATE'),term('TIME'),term('DATETIME'),term('BLOB'),term('MEMO')])).
ebnf_rule(index_col, choice([seq([leaf(identifier),term('DESC')]),seq([leaf(identifier),term('ASC')]),leaf(identifier)])).
ebnf_rule(value_list, one_or_more(nt(value),term(','))).
ebnf_rule(ident_list, one_or_more(leaf(identifier),term(','))).
ebnf_rule(predicate_or, one_or_more(nt(predicate_and),term('OR'))).
ebnf_rule(set_clause, seq([nt(set_lhs),term(=),nt(value)])).
ebnf_rule(modifier, choice([seq([term('WHERE'),nt(predicate_or)]),seq([term('GROUP'),term('BY'),nt(group_by_list)]),seq([term('ORDER'),term('BY'),nt(order_item_list)]),seq([term('HAVING'),nt(predicate_or)]),seq([term('TOP'),leaf(integer_literal)])])).
ebnf_rule(table_or_joined, seq([nt(table_ref),zero_or_more(seq([nt(join_type),nt(table_ref),term('ON'),nt(predicate_or)]))])).
ebnf_rule(column_or_star, seq([nt(column_or_star_bare),nt(column_alias_opt)])).
ebnf_rule(value, nt(additive)).
ebnf_rule(predicate_and, one_or_more(nt(predicate_atom),term('AND'))).
ebnf_rule(set_lhs, choice([seq([leaf(identifier),term('.'),leaf(identifier)]),leaf(identifier)])).
ebnf_rule(order_item_list, one_or_more(nt(order_item),term(','))).
ebnf_rule(group_by_list, one_or_more(nt(value),term(','))).
ebnf_rule(table_ref, choice([seq([nt(table_name),term('AS'),leaf(identifier)]),seq([nt(table_name),leaf(identifier)]),nt(table_name)])).
ebnf_rule(join_type, choice([seq([term('LEFT'),term('OUTER'),term('JOIN')]),seq([term('LEFT'),term('JOIN')]),seq([term('RIGHT'),term('OUTER'),term('JOIN')]),seq([term('RIGHT'),term('JOIN')]),seq([term('INNER'),term('JOIN')]),term('JOIN')])).
ebnf_rule(column_alias_opt, opt(choice([seq([term('AS'),leaf(identifier)]),leaf(identifier)]))).
ebnf_rule(column_or_star_bare, choice([term(*),nt(value)])).
ebnf_rule(additive, seq([nt(multiplicative),zero_or_more(choice([seq([term(+),nt(multiplicative)]),seq([term(-),nt(multiplicative)]),seq([term('||'),nt(multiplicative)])]))])).
ebnf_rule(predicate_atom, choice([seq([term('('),nt(predicate_or),term(')')]),seq([term('NOT'),nt(predicate_atom)]),seq([nt(value),term('IS'),term('NOT'),term('NULL')]),seq([nt(value),term('IS'),term('NULL')]),seq([nt(value),term('NOT'),term('IN'),term('('),nt(in_rhs),term(')')]),seq([nt(value),term('IN'),term('('),nt(in_rhs),term(')')]),seq([nt(value),term('NOT'),term('BETWEEN'),nt(value),term('AND'),nt(value)]),seq([nt(value),term('BETWEEN'),nt(value),term('AND'),nt(value)]),seq([nt(value),term('NOT'),term('LIKE'),leaf(string_literal)]),seq([nt(value),term('LIKE'),leaf(string_literal)]),seq([nt(value),nt(cmp_op),nt(value)]),seq([nt(value),term(=),nt(value)])])).
ebnf_rule(order_item, choice([seq([nt(value),term('DESC')]),seq([nt(value),term('ASC')]),nt(value)])).
ebnf_rule(table_name, choice([seq([leaf(identifier),term(\),leaf(identifier)]),leaf(identifier)])).
ebnf_rule(multiplicative, seq([nt(unary),zero_or_more(choice([seq([term(*),nt(unary)]),seq([term(/),nt(unary)]),seq([term('MOD'),nt(unary)])]))])).
ebnf_rule(cmp_op, choice([term(<=),term(>=),term(<>),term('!='),term(<),term(>)])).
ebnf_rule(in_rhs, choice([nt(select_chain),nt(value_list)])).
ebnf_rule(unary, choice([seq([term(-),nt(unary)]),nt(primary)])).
ebnf_rule(primary, choice([seq([term('('),nt(value),term(')')]),nt(cast_expr),nt(case_expr),nt(function_call),seq([leaf(identifier),term('.'),leaf(identifier)]),term('TRUE'),term('FALSE'),leaf(identifier),leaf(decimal_literal),leaf(integer_literal),leaf(string_literal),term(?)])).
ebnf_rule(function_call, choice([seq([term('EXTRACT'),term('('),nt(extract_field),term('FROM'),nt(value),term(')')]),seq([term('TRIM'),term('('),nt(trim_side),leaf(string_literal),nt(trim_separator),nt(value),term(')')]),seq([term('CONCAT'),term('('),nt(func_arg),term('WITH'),nt(func_arg),term(')')]),seq([leaf(identifier),term('('),nt(func_arg_list),term(')')])])).
ebnf_rule(case_expr, seq([term('CASE'),nt(case_body),term('END')])).
ebnf_rule(cast_expr, seq([term('CAST'),term('('),nt(value),nt(cast_separator),nt(cast_type),term(')')])).
ebnf_rule(func_arg_list, opt(choice([term(*),seq([nt(func_arg),zero_or_more(seq([term(','),nt(value)]))])]))).
ebnf_rule(func_arg, choice([nt(predicate_or),nt(value)])).
ebnf_rule(trim_separator, choice([term('FROM'),term(',')])).
ebnf_rule(trim_side, choice([term('LEADING'),term('TRAILING'),term('BOTH')])).
ebnf_rule(extract_field, choice([term('YEAR'),term('MONTH'),term('WEEK'),term('DAYOFWEEK'),term('DAYOFYEAR'),term('DAY'),term('HOUR'),term('MINUTE'),term('SECOND'),term('MSECOND')])).
ebnf_rule(case_body, choice([seq([nt(case_when_list_searched),nt(case_else_opt)]),seq([nt(value),nt(case_when_list_simple),nt(case_else_opt)])])).
ebnf_rule(cast_separator, choice([term('AS'),term(',')])).
ebnf_rule(case_else_opt, opt(seq([term('ELSE'),nt(value)]))).
ebnf_rule(case_when_list_simple, seq([term('WHEN'),nt(value),term('THEN'),nt(value),nt(case_when_list_simple_more)])).
ebnf_rule(case_when_list_searched, seq([term('WHEN'),nt(predicate_or),term('THEN'),nt(value),nt(case_when_list_searched_more)])).
ebnf_rule(case_when_list_simple_more, opt(nt(case_when_list_simple))).
ebnf_rule(case_when_list_searched_more, opt(nt(case_when_list_searched))).
