% The DBISAM DCG — first slice.
%
% Scope at this commit:
%   - Lexical layer: identifiers, integer literals, single-quoted
%     string literals, whitespace.
%   - Comments: `--` line comments (terminated by `\n`/`\r`/EOF) and
%     `/* */` block comments (non-nesting per DBISAM, see slice #66).
%     Both treated as whitespace-equivalent at the `ws`/`ws1` layer.
%   - One statement: bare `SELECT <column-list> FROM <table>` where
%     column-list is one or more comma-separated identifiers and
%     table is a single identifier.
%
% AST term shape:
%   Top-level: either a bare `select_statement(...)` or a UNION tree.
%     UNION is left-associative — `a UNION b UNION c` parses to
%     `union(union(a, b), c)`. `UNION ALL` uses `union_all/2` likewise.
%
%   select_statement(Distinct, Columns, FromList, Modifiers)
%     where Distinct ∈ {distinct, all_rows} — `distinct` iff the
%                      SELECT clause used the DISTINCT keyword;
%                      `all_rows` is the default (DBISAM's `ALL`
%                      keyword is also accepted as a synonym for the
%                      default).
%     and   Columns  = [Item, ...] and each Item is either
%                      `star` (for `*`) or `identifier(Atom)`,
%     and   FromList = [table(identifier(Name), Alias), ...],
%                      where Alias is `no_alias` or `identifier(A)`.
%                      Single-table is just a one-element list.
%     and   Modifiers = [Clause, ...] in source order; `[]` for the
%                      bare form. Each Clause is a functor like
%                      `top(Integer)`, `where(Pred)`, `group_by([..])`,
%                      `order_by([..])` etc. as the grammar grows.
%     Per Elevate docs §SELECT_Statement, source-order is
%       WHERE, GROUP BY, HAVING, ORDER BY, TOP.
%
% Case handling:
%   - Keywords (SELECT, FROM) are case-insensitive. They are
%     STRUCTURAL only — they don't appear in the AST.
%   - Identifiers (column names, table names) preserve case as
%     written. So `select code from CUSTOMER` and
%     `SELECT code FROM CUSTOMER` produce identical AST terms.
%
% Round-trip discipline:
%   The generator (`generate_statement/2`) emits a CANONICAL form —
%   uppercase keywords, single space separators, no trailing
%   whitespace. The generated SQL is therefore not byte-equal to the
%   original input, but re-parsing the generated SQL produces the
%   same AST term. This is the property CORPUS.md's "Promotion bar"
%   criterion 3 actually requires.
%
% Anti-stub:
%   - No placeholder atoms (`unimplemented`, `todo`, `_` in
%     load-bearing positions).
%   - No catch-all productions matching `[_]` or similar.
%   - Constructs not in this file's scope (TOP n, UNION, WHERE,
%     parenthesised projections, etc.) have NO rule and will fail
%     to parse — which is honest. Future slices will add them.

:- module(dcg, [
    statement//1,
    parse_statement/2,
    generate_statement/2,
    roundtrip_term/2,
    % Lexical layer, exported for reuse by the railroad equivalence gate
    % (railroad/). These are behaviour-inert exports: the gate's EBNF
    % interpreter shares THIS lexer verbatim, so the only thing under
    % test is the extracted production structure, never the tokeniser.
    identifier//1,
    string_literal//1,
    integer_literal//1,
    decimal_literal//1,
    ws//0,
    ws1//0
]).

:- use_module(library(lists)).
:- use_module(library(dcgs)).

% Verified function catalogue from the live engine on rivsem04.
% Auto-generated by tools/probe-functions.sh — see docs/functions.md
% for the human catalogue.
:- use_module('functions.pl').
:- use_module('function_sigs.pl').

% Several predicates have clauses scattered across the file by topic
% rather than packed together. Declare them discontiguous so Scryer
% doesn't drop earlier clauses on a re-encounter. DCG rules need the
% expanded arity (+2 for the in/out difference lists).
:- discontiguous(gen_predicate/2).
:- discontiguous(gen_modifier/2).
:- discontiguous(function_call/3).
:- discontiguous(gen_function_call/2).
:- discontiguous(gen_column/2).
:- discontiguous(gen_value/2).
:- discontiguous(predicate_atom/3).
:- discontiguous(in_rhs/3).
:- discontiguous(generate_statement/2).
:- discontiguous(modifier/3).


% ============================================================
% Public entry points
% ============================================================

% parse_statement(+Chars, -Term)
%   Run the DCG forward. Succeeds iff the input is a syntactically
%   valid statement in the current grammar scope. Fails (no error)
%   if the input doesn't parse.
parse_statement(Chars, Term) :-
    phrase(statement(Term), Chars).

% generate_statement(+Term, -Chars)
%   Run the generator. Emits the canonical SQL form for Term.
generate_statement(union(L, R), Chars) :-
    generate_statement(L, LC),
    generate_statement(R, RC),
    append([LC, [' ','U','N','I','O','N',' '], RC], Chars).
generate_statement(union_all(L, R), Chars) :-
    generate_statement(L, LC),
    generate_statement(R, RC),
    append([LC, [' ','U','N','I','O','N',' ','A','L','L',' '], RC], Chars).
generate_statement(update_statement(Table, Sets, WhereOpt), Chars) :-
    gen_table_name(Table, TC),
    gen_set_list(Sets, SC),
    gen_where_opt(WhereOpt, WC),
    append([['U','P','D','A','T','E',' '], TC, [' ','S','E','T',' '], SC, WC], Chars).
generate_statement(delete_statement(Table, WhereOpt), Chars) :-
    gen_table_name(Table, TC),
    gen_where_opt(WhereOpt, WC),
    append([['D','E','L','E','T','E',' ','F','R','O','M',' '], TC, WC], Chars).
generate_statement(drop_table(Table, IfExists), Chars) :-
    gen_table_name(Table, TC),
    gen_drop_if_exists(IfExists, IfExC),
    append([['D','R','O','P',' ','T','A','B','L','E',' '], IfExC, TC], Chars).
generate_statement(create_index(Name, Table, Cols, Modifier), Chars) :-
    gen_create_index_modifier(Modifier, MC),
    Name  = identifier(NameAtom), gen_ident_atom(NameAtom, NC),
    Table = identifier(TableAtom), gen_ident_atom(TableAtom, TC),
    gen_index_col_list(Cols, ColC),
    append([['C','R','E','A','T','E',' '], MC, ['I','N','D','E','X',' '], NC,
            [' ','O','N',' '], TC, [' ','('], ColC, [')']], Chars).

gen_create_index_modifier(plain,  []).
gen_create_index_modifier(unique, ['U','N','I','Q','U','E',' ']).
gen_create_index_modifier(nocase, ['N','O','C','A','S','E',' ']).

gen_index_col_list([C], Chars) :- gen_index_col(C, Chars).
gen_index_col_list([C|Rest], Chars) :-
    Rest = [_|_],
    gen_index_col(C, CC),
    gen_index_col_list(Rest, RC),
    append([CC, [',',' '], RC], Chars).

gen_index_col(index_col(identifier(A), default), Chars) :- gen_ident_atom(A, Chars).
gen_index_col(index_col(identifier(A), asc), Chars) :-
    gen_ident_atom(A, IC),
    append(IC, [' ','A','S','C'], Chars).
gen_index_col(index_col(identifier(A), desc), Chars) :-
    gen_ident_atom(A, IC),
    append(IC, [' ','D','E','S','C'], Chars).

generate_statement(drop_index(identifier(A)), Chars) :-
    gen_ident_atom(A, IC),
    append(['D','R','O','P',' ','I','N','D','E','X',' '], IC, Chars).
generate_statement(drop_index(qualified(identifier(T), identifier(N))), Chars) :-
    gen_ident_atom(T, TC), gen_ident_atom(N, NC),
    append([['D','R','O','P',' ','I','N','D','E','X',' '], TC, ['.'], NC], Chars).

generate_statement(export_table(Table, File), Chars) :-
    Table = identifier(TA), gen_ident_atom(TA, TC),
    File  = identifier(FA), gen_ident_atom(FA, FC),
    append([['E','X','P','O','R','T',' ','T','A','B','L','E',' '], TC,
            [' ','T','O',' '], FC], Chars).
generate_statement(import_table(Table, File), Chars) :-
    Table = identifier(TA), gen_ident_atom(TA, TC),
    File  = identifier(FA), gen_ident_atom(FA, FC),
    append([['I','M','P','O','R','T',' ','T','A','B','L','E',' '], TC,
            [' ','F','R','O','M',' '], FC], Chars).

generate_statement(maint(Op, Table), Chars) :-
    maint_op_chars(Op, OpC),
    Table = identifier(TableAtom), gen_ident_atom(TableAtom, TC),
    append([OpC, [' ','T','A','B','L','E',' '], TC], Chars).

maint_op_chars(empty,    ['E','M','P','T','Y']).
maint_op_chars(optimize, ['O','P','T','I','M','I','Z','E']).
maint_op_chars(verify,   ['V','E','R','I','F','Y']).
maint_op_chars(repair,   ['R','E','P','A','I','R']).
maint_op_chars(upgrade,  ['U','P','G','R','A','D','E']).

generate_statement(rename_table(Old, New), Chars) :-
    Old = identifier(OldAtom), gen_ident_atom(OldAtom, OC),
    New = identifier(NewAtom), gen_ident_atom(NewAtom, NC),
    append([['R','E','N','A','M','E',' ','T','A','B','L','E',' '], OC,
            [' ','T','O',' '], NC], Chars).

generate_statement(alter_table(Table, add_column(Col, type(TypeAtom, SizeArgs))), Chars) :-
    gen_table_name(Table, TC),
    Col = identifier(ColAtom),
    gen_ident_atom(ColAtom, CC),
    atom_chars(TypeAtom, TyC),
    gen_cast_size(SizeArgs, SC),
    append([['A','L','T','E','R',' ','T','A','B','L','E',' '], TC,
            [' ','A','D','D',' '], CC, [' '], TyC, SC], Chars).

gen_drop_if_exists(no_if_exists, []).
gen_drop_if_exists(if_exists, ['I','F',' ','E','X','I','S','T','S',' ']).

generate_statement(start_transaction, ['S','T','A','R','T',' ','T','R','A','N','S','A','C','T','I','O','N']).
generate_statement(commit(no_work),  ['C','O','M','M','I','T']).
generate_statement(commit(work),     ['C','O','M','M','I','T',' ','W','O','R','K']).
generate_statement(rollback(no_work),['R','O','L','L','B','A','C','K']).
generate_statement(rollback(work),   ['R','O','L','L','B','A','C','K',' ','W','O','R','K']).
generate_statement(insert_statement(Table, ColsOpt, Source), Chars) :-
    gen_table_name(Table, TC),
    gen_insert_cols_opt(ColsOpt, CC),
    gen_insert_source(Source, SC),
    append([['I','N','S','E','R','T',' ','I','N','T','O',' '], TC, CC, [' '], SC], Chars).

gen_insert_cols_opt(no_cols, []).
gen_insert_cols_opt(cols(Cs), Chars) :-
    gen_ident_list(Cs, IC),
    append([[' ','('], IC, [')']], Chars).

gen_insert_source(values(Vs), Chars) :-
    gen_value_list(Vs, VC),
    append([['V','A','L','U','E','S',' ','('], VC, [')']], Chars).
gen_insert_source(from_select(S), Chars) :-
    generate_statement(S, Chars).

gen_set_list([S], Chars) :- gen_set_clause(S, Chars).
gen_set_list([S | Rest], Chars) :-
    Rest = [_|_],
    gen_set_clause(S, SC),
    gen_set_list(Rest, RC),
    append([SC, [',',' '], RC], Chars).

gen_set_clause(set(L, V), Chars) :-
    gen_set_lhs(L, LC),
    gen_value(V, VC),
    append([LC, [' ','=',' '], VC], Chars).

gen_set_lhs(qualified(identifier(Q), identifier(N)), Chars) :-
    gen_ident_atom(Q, QC), gen_ident_atom(N, NC),
    append([QC, ['.'], NC], Chars).
gen_set_lhs(identifier(N), Chars) :- gen_ident_atom(N, Chars).

gen_where_opt(no_where, []).
gen_where_opt(where(P), Chars) :-
    gen_predicate(P, PC),
    append([' ','W','H','E','R','E',' '], PC, Chars).
generate_statement(select_statement(Distinct, Columns, FromList, Mods), Chars) :-
    gen_distinct(Distinct, DistChars),
    gen_columns(Columns, ColChars),
    gen_from_list(FromList, FromChars),
    gen_modifiers(Mods, ModChars),
    append([
        ['S','E','L','E','C','T',' '],
        DistChars,
        ColChars,
        [' ','F','R','O','M',' '],
        FromChars,
        ModChars
    ], Chars).
generate_statement(select_into(Table, select_statement(Distinct, Columns, FromList, Mods)), Chars) :-
    gen_distinct(Distinct, DistChars),
    gen_columns(Columns, ColChars),
    gen_table_name(Table, TC),
    gen_from_list(FromList, FromChars),
    gen_modifiers(Mods, ModChars),
    append([
        ['S','E','L','E','C','T',' '],
        DistChars,
        ColChars,
        [' ','I','N','T','O',' '],
        TC,
        [' ','F','R','O','M',' '],
        FromChars,
        ModChars
    ], Chars).

gen_distinct(all_rows, []).
gen_distinct(distinct, ['D','I','S','T','I','N','C','T',' ']).

gen_from_list([T], Chars) :- gen_table_ref(T, Chars).
gen_from_list([T | Rest], Chars) :-
    Rest = [_|_],
    gen_table_ref(T, TC),
    gen_from_list(Rest, RC),
    append([TC, [',',' '], RC], Chars).

gen_table_ref(table(N, no_alias), Chars) :-
    gen_table_name(N, Chars).
gen_table_ref(table(N, identifier(A)), Chars) :-
    gen_table_name(N, NC),
    gen_ident_atom(A, AC),
    append([NC, [' '], AC], Chars).
gen_table_ref(joined(Type, L, R, OnPred), Chars) :-
    gen_table_ref(L, LC),
    join_type_chars(Type, JTC),
    gen_table_ref(R, RC),
    gen_predicate(OnPred, OC),
    append([LC, [' '], JTC, [' '], RC, [' ','O','N',' '], OC], Chars).

join_type_chars(inner, ['I','N','N','E','R',' ','J','O','I','N']).
join_type_chars(left,  ['L','E','F','T',' ','J','O','I','N']).
join_type_chars(right, ['R','I','G','H','T',' ','J','O','I','N']).

gen_table_name(identifier(N), Chars) :- gen_ident_atom(N, Chars).
gen_table_name(catalog_qualified(identifier(C), identifier(T)), Chars) :-
    gen_ident_atom(C, CC), gen_ident_atom(T, TC),
    append([CC, ['\\'], TC], Chars).

gen_modifiers([], []).
gen_modifiers([M|Ms], Chars) :-
    gen_modifier(M, MChars),
    gen_modifiers(Ms, RestChars),
    append([[' '], MChars, RestChars], Chars).

gen_modifier(top(N), Chars) :-
    number_chars(N, NChars),
    append(['T','O','P',' '], NChars, Chars).
gen_modifier(where(Pred), Chars) :-
    gen_predicate(Pred, PChars),
    append(['W','H','E','R','E',' '], PChars, Chars).
gen_modifier(group_by(Cols), Chars) :-
    gen_value_list(Cols, ColChars),
    append(['G','R','O','U','P',' ','B','Y',' '], ColChars, Chars).
gen_modifier(order_by(Os), Chars) :-
    gen_order_items(Os, OC),
    append(['O','R','D','E','R',' ','B','Y',' '], OC, Chars).
gen_modifier(having(P), Chars) :-
    gen_predicate(P, PC),
    append(['H','A','V','I','N','G',' '], PC, Chars).

gen_order_items([O], Chars) :- gen_order_item(O, Chars).
gen_order_items([O|Rest], Chars) :-
    Rest = [_|_],
    gen_order_item(O, OC),
    gen_order_items(Rest, RC),
    append([OC, [',',' '], RC], Chars).

gen_order_item(ord(V, asc), Chars) :- gen_value(V, Chars).
gen_order_item(ord(V, desc), Chars) :-
    gen_value(V, VC),
    append(VC, [' ','D','E','S','C'], Chars).

gen_ident_list([identifier(A)], Chars) :- gen_ident_atom(A, Chars).
gen_ident_list([identifier(A) | Rest], Chars) :-
    Rest = [_|_],
    gen_ident_atom(A, AC),
    gen_ident_list(Rest, RC),
    append([AC, [',',' '], RC], Chars).

gen_predicate(eq(L, R), Chars) :-
    gen_value(L, LChars),
    gen_value(R, RChars),
    append([LChars, [' ','=',' '], RChars], Chars).
gen_predicate(is_null(L), Chars) :-
    gen_value(L, LChars),
    append(LChars, [' ','I','S',' ','N','U','L','L'], Chars).
gen_predicate(is_not_null(L), Chars) :-
    gen_value(L, LChars),
    append(LChars, [' ','I','S',' ','N','O','T',' ','N','U','L','L'], Chars).
% AND binds tighter than OR. The generator must insert parens
% wherever default precedence + left-associativity would re-parse to
% a different AST than the one we're generating. Cases:
%
%   AND/L: wrap if L is or(_,_)  -- precedence preservation
%   AND/R: wrap if R is or(_,_)  -- precedence preservation
%          wrap if R is and(_,_) -- right-assoc preservation
%                                   (default re-parse is left-assoc)
%   OR/L:  never wrap  (lowest precedence, left-assoc default)
%   OR/R:  wrap if R is or(_,_)  -- right-assoc preservation
gen_predicate(and(L, R), Chars) :-
    gen_pred_paren_if(L, [or], LC),
    gen_pred_paren_if(R, [or, and], RC),
    append([LC, [' ','A','N','D',' '], RC], Chars).
gen_predicate(or(L, R), Chars) :-
    gen_predicate(L, LC),
    gen_pred_paren_if(R, [or], RC),
    append([LC, [' ','O','R',' '], RC], Chars).

% Wrap predicate P in parens iff its outer functor is in the WrapList.
gen_pred_paren_if(P, WrapList, Chars) :-
    ( functor(P, F, _),
      member(F, WrapList)
    -> gen_predicate(P, PC),
       append([['('], PC, [')']], Chars)
    ;  gen_predicate(P, Chars)
    ).
gen_predicate(cmp(Op, L, R), Chars) :-
    gen_value(L, LC), gen_value(R, RC),
    cmp_op_chars(Op, OC),
    append([LC, [' '], OC, [' '], RC], Chars).
gen_predicate(like(L, R), Chars) :-
    gen_value(L, LC), gen_value(R, RC),
    append([LC, [' ','L','I','K','E',' '], RC], Chars).
gen_predicate(not_like(L, R), Chars) :-
    gen_value(L, LC), gen_value(R, RC),
    append([LC, [' ','N','O','T',' ','L','I','K','E',' '], RC], Chars).
gen_predicate(not(P), Chars) :-
    gen_predicate(P, PC),
    append(['N','O','T',' ','('], PC, P1),
    append(P1, [')'], Chars).
gen_predicate(in(L, Rhs), Chars) :-
    gen_value(L, LC),
    gen_in_rhs(Rhs, RC),
    append([LC, [' ','I','N',' ','('], RC, [')']], Chars).
gen_predicate(not_in(L, Rhs), Chars) :-
    gen_value(L, LC),
    gen_in_rhs(Rhs, RC),
    append([LC, [' ','N','O','T',' ','I','N',' ','('], RC, [')']], Chars).
gen_predicate(between(V, Lo, Hi), Chars) :-
    gen_value(V, VC), gen_value(Lo, LoC), gen_value(Hi, HiC),
    append([VC, [' ','B','E','T','W','E','E','N',' '], LoC,
            [' ','A','N','D',' '], HiC], Chars).
gen_predicate(not_between(V, Lo, Hi), Chars) :-
    gen_value(V, VC), gen_value(Lo, LoC), gen_value(Hi, HiC),
    append([VC, [' ','N','O','T',' ','B','E','T','W','E','E','N',' '], LoC,
            [' ','A','N','D',' '], HiC], Chars).

gen_in_rhs(subselect(S), Chars) :- generate_statement(S, Chars).
gen_in_rhs(Vs, Chars) :-
    Vs = [_|_],
    gen_value_list(Vs, Chars).

cmp_op_chars(lt, ['<']).
cmp_op_chars(gt, ['>']).
cmp_op_chars(le, ['<','=']).
cmp_op_chars(ge, ['>','=']).
cmp_op_chars(ne, ['<','>']).

gen_value_list([V], Chars) :- gen_value(V, Chars).
gen_value_list([V|Rest], Chars) :-
    Rest = [_|_],
    gen_value(V, VC),
    gen_value_list(Rest, RC),
    append([VC, [',',' '], RC], Chars).

gen_value(identifier(A), Chars) :- gen_ident_atom(A, Chars).
gen_value(string_literal(A), Chars) :-
    atom_chars(A, Inner),
    escape_quotes(Inner, Escaped),
    append([[''''], Escaped, [''''] ], Chars).

% Double any embedded `'` for round-trip into source form — the
% inverse of the parser's `''` → `'` rule. Anything else passes
% through unchanged.
escape_quotes([], []).
escape_quotes([''''|Cs], ['''', ''''|Es]) :- escape_quotes(Cs, Es).
escape_quotes([C|Cs], [C|Es]) :- C \== '''', escape_quotes(Cs, Es).
gen_value(integer_literal(N), Chars) :- number_chars(N, Chars).
gen_value(decimal_literal(A), Chars) :- atom_chars(A, Chars).
gen_value(boolean_literal(true),  ['T','R','U','E']).
gen_value(boolean_literal(false), ['F','A','L','S','E']).
gen_value(parameter(positional), ['?']).
% Predicate-shaped values (as function-call args, etc.). Delegate to
% gen_predicate which already handles every predicate atom shape.
gen_value(cmp(Op, L, R), Chars)     :- gen_predicate(cmp(Op, L, R), Chars).
gen_value(eq(L, R), Chars)          :- gen_predicate(eq(L, R), Chars).
gen_value(is_null(V), Chars)        :- gen_predicate(is_null(V), Chars).
gen_value(is_not_null(V), Chars)    :- gen_predicate(is_not_null(V), Chars).
gen_value(like(L, R), Chars)        :- gen_predicate(like(L, R), Chars).
gen_value(in(L, Rhs), Chars)        :- gen_predicate(in(L, Rhs), Chars).
gen_value(not_in(L, Rhs), Chars)    :- gen_predicate(not_in(L, Rhs), Chars).
gen_value(and(L, R), Chars)         :- gen_predicate(and(L, R), Chars).
gen_value(or(L, R), Chars)          :- gen_predicate(or(L, R), Chars).
gen_value(qualified(identifier(Q), identifier(N)), Chars) :-
    gen_ident_atom(Q, QC), gen_ident_atom(N, NC),
    append([QC, ['.'], NC], Chars).
gen_value(cast(E, T), Chars) :- gen_cast(cast(E, T), Chars).
gen_value(function_call(N, Args), Chars) :- gen_function_call(function_call(N, Args), Chars).
gen_value(extract(F, E), Chars) :- gen_function_call(extract(F, E), Chars).
gen_value(trim(S, C, E), Chars) :- gen_function_call(trim(S, C, E), Chars).
gen_value(arith(Op, L, R), Chars) :-
    arith_prec(Op, P),
    gen_arith_left(L, P, LC),
    arith_op_chars(Op, OC),
    gen_arith_right(R, P, RC),
    append([LC, OC, RC], Chars).
gen_value(neg(V), Chars) :-
    ( V = arith(_, _, _) ; V = neg(_) )
    -> ( gen_value(V, VC), append([['-','('], VC, [')']], Chars) )
    ;  ( gen_value(V, VC), append([['-'], VC], Chars) ).
gen_value(case_when(Whens, Else), Chars) :-
    gen_case_when_searched(Whens, WC),
    gen_case_else(Else, EC),
    append([['C','A','S','E',' '], WC, EC, [' ','E','N','D']], Chars).
gen_value(case_match(Expr, Whens, Else), Chars) :-
    gen_value(Expr, ExC),
    gen_case_when_simple(Whens, WC),
    gen_case_else(Else, EC),
    append([['C','A','S','E',' '], ExC, [' '], WC, EC, [' ','E','N','D']], Chars).

gen_case_when_searched([when(C, R)], Chars) :-
    gen_predicate(C, CC),
    gen_value(R, RC),
    append([['W','H','E','N',' '], CC, [' ','T','H','E','N',' '], RC], Chars).
gen_case_when_searched([when(C, R) | Rest], Chars) :-
    Rest = [_|_],
    gen_predicate(C, CC),
    gen_value(R, RC),
    gen_case_when_searched(Rest, RestC),
    append([['W','H','E','N',' '], CC, [' ','T','H','E','N',' '], RC, [' '], RestC], Chars).

gen_case_when_simple([when(V, R)], Chars) :-
    gen_value(V, VC),
    gen_value(R, RC),
    append([['W','H','E','N',' '], VC, [' ','T','H','E','N',' '], RC], Chars).
gen_case_when_simple([when(V, R) | Rest], Chars) :-
    Rest = [_|_],
    gen_value(V, VC),
    gen_value(R, RC),
    gen_case_when_simple(Rest, RestC),
    append([['W','H','E','N',' '], VC, [' ','T','H','E','N',' '], RC, [' '], RestC], Chars).

gen_case_else(no_else, []).
gen_case_else(else(V), Chars) :-
    gen_value(V, VC),
    append([' ','E','L','S','E',' '], VC, Chars).

% Operator precedence (higher binds tighter).
arith_prec(add,    1).
arith_prec(sub,    1).
arith_prec(concat, 1).
arith_prec(mul,    2).
arith_prec(div,    2).
arith_prec(mod,    2).

arith_op_chars(add,    [' ','+',' ']).
arith_op_chars(sub,    [' ','-',' ']).
arith_op_chars(concat, [' ','|','|',' ']).
arith_op_chars(mul,    [' ','*',' ']).
arith_op_chars(div,    [' ','/',' ']).
arith_op_chars(mod,    [' ','M','O','D',' ']).

% Left operand: wrap if it's an arith with strictly lower precedence
% than the surrounding op. Same-precedence left operands need no
% parens — left-associative grouping is the parser default.
gen_arith_left(arith(LOp, L1, R1), P, Chars) :-
    arith_prec(LOp, LP),
    LP < P, !,
    gen_value(arith(LOp, L1, R1), Inner),
    append([['('], Inner, [')']], Chars).
gen_arith_left(V, _, Chars) :- gen_value(V, Chars).

% Right operand: wrap if it's an arith with precedence less-than-or-equal
% to the surrounding op. Equal precedence on the right needs parens
% because left-assoc reparse would re-group otherwise.
gen_arith_right(arith(ROp, L1, R1), P, Chars) :-
    arith_prec(ROp, RP),
    RP =< P, !,
    gen_value(arith(ROp, L1, R1), Inner),
    append([['('], Inner, [')']], Chars).
gen_arith_right(V, _, Chars) :- gen_value(V, Chars).

gen_function_call(function_call(NameAtom, Args), Chars) :-
    atom_chars(NameAtom, NameChars),
    gen_func_args(Args, ArgChars),
    append([NameChars, ['('], ArgChars, [')']], Chars).
gen_function_call(extract(Field, Expr), Chars) :-
    atom_chars(Field, FC),
    gen_value(Expr, EC),
    append([['E','X','T','R','A','C','T','('], FC, [' ','F','R','O','M',' '], EC, [')']], Chars).
gen_function_call(trim(Side, CharsLit, Expr), Chars) :-
    trim_side_chars(Side, SC),
    gen_value(CharsLit, CC),
    gen_value(Expr, EC),
    append([['T','R','I','M','('], SC, [' '], CC, [' ','F','R','O','M',' '], EC, [')']], Chars).

trim_side_chars(leading,  ['L','E','A','D','I','N','G']).
trim_side_chars(trailing, ['T','R','A','I','L','I','N','G']).
trim_side_chars(both,     ['B','O','T','H']).

gen_func_args([], []).
gen_func_args([star], ['*']).
gen_func_args([A], Chars) :-
    A \= star,
    gen_value(A, Chars).
gen_func_args([A|Rest], Chars) :-
    Rest = [_|_],
    gen_value(A, AC),
    gen_func_args(Rest, RC),
    append([AC, [',',' '], RC], Chars).

gen_cast(cast(E, type(TypeAtom, SizeArgs)), Chars) :-
    gen_value(E, EC),
    atom_chars(TypeAtom, TC),
    gen_cast_size(SizeArgs, SC),
    append([['C','A','S','T','('], EC, [' ','A','S',' '], TC, SC, [')']], Chars).

gen_cast_size([], []).
gen_cast_size([Size], Chars) :-
    number_chars(Size, NC),
    append(['('], NC, P1),
    append(P1, [')'], Chars).

gen_columns([C], Chars) :-
    gen_column(C, Chars).
gen_columns([C | Rest], Chars) :-
    Rest = [_|_],
    gen_column(C, CChars),
    gen_columns(Rest, RestChars),
    append([CChars, [',',' '], RestChars], Chars).

gen_column(star, ['*']).
gen_column(aliased(Item, identifier(A)), Chars) :-
    gen_column(Item, IC),
    gen_ident_atom(A, AC),
    append([IC, [' ','A','S',' '], AC], Chars).
% Any other projection item is just a value expression — delegate
% to the value generator. This keeps gen_column in sync with
% column_or_star_bare//1, which itself delegates to value//1.
gen_column(Item, Chars) :-
    Item \= star,
    Item \= aliased(_, _),
    gen_value(Item, Chars).

% roundtrip_term(+Term, -Term2)
%   Generate Term to SQL, re-parse, return the resulting term.
%   Succeeds iff the regeneration round-trips cleanly. Used by the
%   promotion checker.
roundtrip_term(Term, Term2) :-
    generate_statement(Term, Chars),
    parse_statement(Chars, Term2).


% ============================================================
% Statement
% ============================================================

% Public entry: a top-level statement is either an UPDATE or a
% SELECT (possibly chained by UNION/UNION ALL). UPDATE first because
% it has a distinctive opening keyword and there's no ambiguity.
%
% `select_chain//1` is the SELECT-or-UNION-tree predicate, used both
% here AND inside IN-subqueries (`in_rhs`). Keeping it separate from
% `statement//1` means subqueries can't accidentally accept UPDATE
% syntax — DBISAM rejects `WHERE col IN (UPDATE …)` at parse time,
% and the grammar should match that strictness.
statement(S) -->
    ws,
    statement_body(S),
    trailing_semicolon_opt.

statement_body(S) --> update_statement(S).
statement_body(S) --> delete_statement(S).
statement_body(S) --> insert_statement(S).
statement_body(S) --> drop_table_statement(S).
statement_body(S) --> drop_index_statement(S).
statement_body(S) --> create_index_statement(S).
statement_body(S) --> alter_table_statement(S).
statement_body(S) --> rename_statement(S).
statement_body(S) --> maint_statement(S).
statement_body(S) --> export_statement(S).
statement_body(S) --> import_statement(S).
statement_body(S) --> transaction_statement(S).
statement_body(S) --> select_chain(S).

select_chain(S) -->
    select_statement(L),
    union_rest(L, S).

% Optional trailing `;`. DBISAM accepts (and ignores) a single
% semicolon after a top-level statement — Power-BI-generated SQL
% routinely appends one. No AST node; the `;` is not load-bearing.
trailing_semicolon_opt --> ws, [';'], ws.
trailing_semicolon_opt --> [].

% UPDATE — single-table only. Probed on rivsem04 (slice #44):
%   UPDATE <table> SET <col> = <expr> [, <col> = <expr> ...]
%                  [WHERE <pred>]
% Multi-column SET is supported (the engine accepts comma-separated
% assignments); rejections we initially saw turned out to be schema
% validation on column names. Qualified LHS (`product.price = 0`)
% accepts. No table-alias form needed for now — corpus uses bare.
update_statement(update_statement(Table, Sets, WhereOpt)) -->
    keyword(update),
    ws1, identifier(Table),
    ws1, keyword(set),
    ws1, set_clause_list(Sets),
    where_opt(WhereOpt),
    ws.

set_clause_list([S|Ss]) -->
    set_clause(S),
    set_clause_list_rest(Ss).
set_clause_list_rest([]) --> [].
set_clause_list_rest([S|Ss]) -->
    ws, [','], ws,
    set_clause(S),
    set_clause_list_rest(Ss).

set_clause(set(L, V)) -->
    set_lhs(L),
    ws, ['='], ws,
    value(V).

set_lhs(qualified(Q, N)) --> identifier(Q), ['.'], identifier(N).
set_lhs(L) --> identifier(L).

where_opt(where(P)) --> ws1, keyword(where), ws1, predicate_or(P).
where_opt(no_where) --> [].

% INSERT — two source forms, probed on rivsem04 (slice #49):
%   INSERT INTO <table> [(<col>, ...)] VALUES (<expr>, ...)
%   INSERT INTO <table> [(<col>, ...)] <SELECT-or-UNION-chain>
%
% Notable DBISAM restrictions (engine rejects at parse time):
%   • Multi-row VALUES (`VALUES (1), (2)`) is REJECTED with
%     "Expected end of statement but instead found ,". Single tuple
%     only.
%   • Scalar subqueries in VALUES (`VALUES ((SELECT …))`) are also
%     rejected — consistent with the fussy-subqueries rule.
%   • Empty VALUES list `VALUES ()` is rejected.
%   • INTO keyword is required; bare `INSERT <table>` rejected.
%
% AST:
%   insert_statement(Table, ColsOpt, Source)
%     ColsOpt = cols([identifier(C), ...]) | no_cols
%     Source  = values([V, V, ...]) | from_select(SelectTerm)
insert_statement(insert_statement(Table, ColsOpt, Source)) -->
    keyword(insert),
    ws1, keyword(into),
    ws1, identifier(Table),
    ws,
    insert_cols_opt(ColsOpt),
    insert_source(Source),
    ws.

insert_cols_opt(cols(Cs)) -->
    ['('], ws, ident_list(Cs), ws, [')'], ws.
insert_cols_opt(no_cols) --> [].

insert_source(values(Vs)) -->
    keyword(values),
    ws, ['('], ws,
    value_list(Vs),
    ws, [')'].
insert_source(from_select(S)) -->
    select_chain(S).

% DELETE — single-table only. Probed on rivsem04 (slice #48):
%   DELETE FROM <table> [WHERE <pred>]
% The `FROM` keyword is required — bare `DELETE <table>` is rejected
% with "Expected FROM but instead found <name> in DELETE SQL
% statement". Table aliasing (`DELETE FROM product p WHERE p.code = …`)
% IS accepted by the engine but no corpus entry needs it, so the
% grammar stays bare-table-only for now; add alias support when a
% real-world entry surfaces.
delete_statement(delete_statement(Table, WhereOpt)) -->
    keyword(delete),
    ws1, keyword(from),
    ws1, identifier(Table),
    where_opt(WhereOpt),
    ws.

% DROP TABLE — probed on rivsem04 (slice #63). The engine silently
% accepts a drop on a missing table, so the optional `IF EXISTS`
% clause is semantically redundant but syntactically supported. The
% grammar preserves whichever form was written. Engine error on
% bare `DROP <name>`: "Expected TABLE or INDEX" — second token must
% be TABLE (we only model TABLE here; INDEX is a separate slice).
drop_table_statement(drop_table(Table, IfExists)) -->
    keyword(drop),
    ws1, keyword(table),
    ws1, drop_if_exists_opt(IfExists),
    identifier(Table),
    ws.

drop_if_exists_opt(if_exists) -->
    keyword(if),
    ws1, keyword(exists),
    ws1.
drop_if_exists_opt(no_if_exists) --> [].

% Transaction control — probed slice #64. DBISAM follows SQL
% standard exactly:
%   START TRANSACTION        (TRANSACTION is mandatory; bare START rejected)
%   COMMIT [WORK]            (TRANSACTION here rejected; only optional WORK)
%   ROLLBACK [WORK]          (same — no TRANSACTION, no savepoints)
%
% No qualifiers (READ ONLY/READ WRITE/ISOLATION LEVEL/etc.), no
% savepoints. AST: bare atoms for the three forms, with the optional
% WORK marker preserved for round-trip.
%
% Try the longer (WORK) variant first so we consume it greedily; if
% the input lacks WORK, backtracking falls to the bare form.
transaction_statement(start_transaction) -->
    keyword(start), ws1, keyword(transaction), ws.
transaction_statement(commit(work)) -->
    keyword(commit), ws1, keyword(work), ws.
transaction_statement(commit(no_work)) -->
    keyword(commit), ws.
transaction_statement(rollback(work)) -->
    keyword(rollback), ws1, keyword(work), ws.
transaction_statement(rollback(no_work)) -->
    keyword(rollback), ws.

% CREATE INDEX — probed slice #69. Engine accepts the syntax
% (reqcode 0x2b05 in our test env is operational, not parse).
% Shapes: `CREATE [UNIQUE|NOCASE] INDEX <name> ON <table> (<cols>)`.
% Per-column direction modifier (`ASC` / `DESC`) is admissible.
% UNIQUE and NOCASE are mutually exclusive modifiers per the
% statement-vocabulary memory's "CREATE TABLE, INDEX, UNIQUE, NOCASE"
% enumeration.
create_index_statement(create_index(Name, Table, Cols, Modifier)) -->
    keyword(create),
    ws1, create_index_modifier(Modifier),
    keyword(index),
    ws1, identifier(Name),
    ws1, keyword(on),
    ws1, identifier(Table),
    ws, ['('], ws,
    index_col_list(Cols),
    ws, [')'],
    ws.

create_index_modifier(unique) --> keyword(unique), ws1.
create_index_modifier(nocase) --> keyword(nocase), ws1.
create_index_modifier(plain)  --> [].

index_col_list([C|Cs]) --> index_col(C), index_col_list_rest(Cs).
index_col_list_rest([]) --> [].
index_col_list_rest([C|Cs]) -->
    ws, [','], ws,
    index_col(C),
    index_col_list_rest(Cs).

index_col(index_col(Col, desc))    --> identifier(Col), ws1, keyword(desc).
index_col(index_col(Col, asc))     --> identifier(Col), ws1, keyword(asc).
index_col(index_col(Col, default)) --> identifier(Col).

% DROP INDEX — DBISAM-specific syntax. Probed slice #69: accepts
% bare `DROP INDEX <name>` and qualified `DROP INDEX <table>.<name>`.
% The SQL-standard `DROP INDEX <name> ON <table>` form is REJECTED
% ("Expected end of statement but instead found ON").
drop_index_statement(drop_index(qualified(Table, Name))) -->
    keyword(drop),
    ws1, keyword(index),
    ws1, identifier(Table), ['.'], identifier(Name),
    ws.
drop_index_statement(drop_index(Name)) -->
    keyword(drop),
    ws1, keyword(index),
    ws1, identifier(Name),
    ws.

% EXPORT TABLE / IMPORT TABLE — bulk data interchange. Probed slice #72:
%   EXPORT TABLE <table> TO <file>
%   IMPORT TABLE <table> FROM <file>
% TABLE keyword required, table name required, TO/FROM keyword
% required, file name required. The file name slot accepts an
% IDENTIFIER (bare, double-quoted, or bracketed) — NOT a string
% literal: `EXPORT TABLE foo TO 'foo.csv'` is REJECTED with
% "Expected file name but instead found 'foo.csv'". So a path with
% slashes/dots has to be double-quoted: `EXPORT TABLE foo TO "/tmp/foo.csv"`.
% This is unusual (most engines treat file paths as string literals)
% but it's how DBISAM was modelled — file names are object names.
export_statement(export_table(Table, File)) -->
    keyword(export),
    ws1, keyword(table),
    ws1, identifier(Table),
    ws1, keyword(to),
    ws1, identifier(File),
    ws.

import_statement(import_table(Table, File)) -->
    keyword(import),
    ws1, keyword(table),
    ws1, identifier(Table),
    ws1, keyword(from),
    ws1, identifier(File),
    ws.

% Maintenance statements — probed slice #71. EMPTY, OPTIMIZE,
% VERIFY, REPAIR, UPGRADE all share the same shape:
%
%   <KEYWORD> TABLE <name>
%
% Bare keyword rejected with "Missing TABLE". `KEYWORD <name>` (no
% TABLE) rejected with "Expected TABLE but instead found <name>".
% `KEYWORD TABLE` alone rejected with "Missing table name". So the
% three tokens are all mandatory. EMPTY TABLE accepted operationally
% (truncates); the others returned 0x2c18 in our test env (syntax
% admissible, operational rejection on the temp table).
%
% AST: `maint(Op, Table)` where Op ∈ {empty, optimize, verify, repair, upgrade}.
maint_statement(maint(Op, Table)) -->
    maint_op(Op),
    ws1, keyword(table),
    ws1, identifier(Table),
    ws.

maint_op(empty)    --> keyword(empty).
maint_op(optimize) --> keyword(optimize).
maint_op(verify)   --> keyword(verify).
maint_op(repair)   --> keyword(repair).
maint_op(upgrade)  --> keyword(upgrade).

% RENAME TABLE — probed slice #70. DBISAM accepts the single-pair
% form only: `RENAME TABLE <old> TO <new>`. Multi-pair (`old1 TO
% new1, old2 TO new2`) rejected. Bare `RENAME <name>` (no TABLE)
% rejected — TABLE is the only second-token RENAME accepts. The
% operational reqcode in our test env is 0x2c18 (the table can't be
% renamed in this transaction context), but the syntax parses.
rename_statement(rename_table(Old, New)) -->
    keyword(rename),
    ws1, keyword(table),
    ws1, identifier(Old),
    ws1, keyword(to),
    ws1, identifier(New),
    ws.

% ALTER TABLE — DBISAM has a narrow ALTER syntax. Probed slice #68:
% the only clearly-accepted syntactic shape is `ALTER TABLE <name>
% ADD <col> <type>`. Engine rejects standard forms like RENAME
% COLUMN, ALTER COLUMN, DROP COLUMN, ADD COLUMN (with explicit
% COLUMN keyword), MODIFY/CHANGE.
%
% Other potentially-accepted forms (ADD PRIMARY KEY, etc.) exist but
% the engine errors with reqcode 0x2b05 (operational, not syntax)
% in our test environment — syntax is admissible but our temp
% tables can't accept the operation. Minimal grammar coverage for
% now; extend when a corpus entry demands a richer form.
alter_table_statement(alter_table(Table, add_column(Col, Type))) -->
    keyword(alter),
    ws1, keyword(table),
    ws1, identifier(Table),
    ws1, keyword(add),
    ws1, identifier(Col),
    ws1, cast_type(Type),
    ws.

% Left-associative accumulator: `a UNION b UNION c` -> union(union(a,b),c).
% Try UNION ALL before bare UNION because of the longer keyword prefix.
union_rest(L, S) -->
    ws1, keyword(union),
    ws1, keyword(all),
    ws1, select_statement(R),
    union_rest(union_all(L, R), S).
union_rest(L, S) -->
    ws1, keyword(union),
    ws1, select_statement(R),
    union_rest(union(L, R), S).
union_rest(S, S) --> [].

% SELECT INTO — DBISAM's CTE-substitute pattern. Syntax:
%   SELECT <cols> INTO <table> FROM <rest>
% INTO sits between the column list and FROM. Probed slice (#58):
% creates a real table as a side effect, so the engine fully accepts
% it; the grammar's job is purely shape. AST wraps the regular SELECT
% in `select_into(Table, select_statement(...))` per option (c) of
% the slice plan — minimal migration. Try the INTO form first so the
% INTO keyword gets consumed before the no-INTO rule's mandatory
% `FROM` match attempts.
select_statement(select_into(Table, select_statement(Distinct, Columns, FromList, Mods))) -->
    keyword(select),
    ws1,
    distinct_opt(Distinct),
    column_list(Columns),
    ws1, keyword(into),
    ws1, identifier(Table),
    ws1, keyword(from),
    ws1,
    table_ref_list(FromList),
    modifier_list(Mods),
    ws.
select_statement(select_statement(Distinct, Columns, FromList, Mods)) -->
    keyword(select),
    ws1,
    distinct_opt(Distinct),
    column_list(Columns),
    ws1,
    keyword(from),
    ws1,
    table_ref_list(FromList),
    modifier_list(Mods),
    ws.

% Optional DISTINCT (or ALL) flag immediately after SELECT. DBISAM
% accepts both forms; ALL is the default behaviour, so we keep the
% AST representation simple — `all_rows` for default/ALL, `distinct`
% for DISTINCT.
distinct_opt(distinct) --> keyword(distinct), ws1.
distinct_opt(all_rows) --> keyword(all), ws1.
distinct_opt(all_rows) --> [].

% Comma-separated table references with optional aliases, plus
% explicit JOINs:
%   FROM customer
%   FROM customer c
%   FROM customer AS c
%   FROM orderh, orderi                       -- comma form
%   FROM a JOIN b ON pred                     -- bare JOIN = INNER
%   FROM a INNER JOIN b ON pred
%   FROM a LEFT JOIN b ON pred
%   FROM a LEFT OUTER JOIN b ON pred          -- OUTER optional
%   FROM a RIGHT JOIN b ON pred
%   FROM a LEFT JOIN b ON p1 LEFT JOIN c ON p2  -- chained, left-assoc
% Each list element is either:
%   table(identifier(Name), Alias)
%   joined(Type, Left, Right, OnPred)
% where Type ∈ {inner, left, right} and Left/Right are themselves
% table-or-joined nodes. Chains nest as
%   joined(left, joined(left, A, B, P1), C, P2).
table_ref_list([T|Ts]) -->
    table_or_joined(T),
    table_ref_list_rest(Ts).

table_ref_list_rest([]) --> [].
table_ref_list_rest([T|Ts]) -->
    ws, [','], ws,
    table_or_joined(T),
    table_ref_list_rest(Ts).

% Parse a single comma-list element. Tail-recursive accumulator over
% any chain of JOIN ... ON ... clauses; left-associative.
table_or_joined(T) -->
    table_ref(T0),
    join_rest(T0, T).

join_rest(L, T) -->
    ws1, join_type(Type),
    ws1, table_ref(R),
    ws1, keyword(on),
    ws1, predicate_or(OnPred),
    join_rest(joined(Type, L, R, OnPred), T).
join_rest(T, T) --> [].

% Try the longest prefixes first: LEFT OUTER JOIN before LEFT JOIN.
% DBISAM does not support FULL OUTER / CROSS / USING — rejected at
% parse time by the engine, so the grammar omits them too.
join_type(left)  --> keyword(left),  ws1, keyword(outer), ws1, keyword(join).
join_type(left)  --> keyword(left),  ws1, keyword(join).
join_type(right) --> keyword(right), ws1, keyword(outer), ws1, keyword(join).
join_type(right) --> keyword(right), ws1, keyword(join).
join_type(inner) --> keyword(inner), ws1, keyword(join).
join_type(inner) --> keyword(join).

% Try aliased forms first. Order: explicit `AS` → implicit-with-guard
% → bare. The implicit-alias guard rejects following identifiers that
% are actually next-clause keywords (WHERE, GROUP, TOP, ORDER, HAVING,
% UNION) — without it, `FROM customer WHERE ...` would consume `WHERE`
% as a column alias.
%
% Table names can be catalog-qualified per DBISAM's `<catalog>\<table>`
% notation (e.g. `NISAINT_CS\Analysis`). The catalog_qualified term
% wraps the catalog + table identifiers.
table_ref(table(N, A)) -->
    table_name(N),
    ws1, keyword(as),
    ws1, identifier(A).
table_ref(table(N, identifier(AliasAtom))) -->
    table_name(N),
    ws1, identifier(identifier(AliasAtom)),
    { atom_lower(AliasAtom, Lower),
      \+ is_table_terminator(Lower) }.
table_ref(table(N, no_alias)) -->
    table_name(N).

% Table name with optional catalog prefix.
table_name(catalog_qualified(C, T)) -->
    identifier(C), ['\\'], identifier(T).
table_name(N) --> identifier(N).

% Lowercase keywords that, if seen after a table name in identifier
% form, are NOT aliases. Match is case-insensitive via atom_lower/2.
is_table_terminator(where).
is_table_terminator(group).
is_table_terminator(top).
is_table_terminator(order).
is_table_terminator(having).
is_table_terminator(union).
is_table_terminator(as).
is_table_terminator(inner).
is_table_terminator(left).
is_table_terminator(right).
is_table_terminator(outer).
is_table_terminator(join).
is_table_terminator(on).

atom_lower(A, L) :-
    atom_chars(A, Cs),
    maplist(to_lower, Cs, LCs),
    atom_chars(L, LCs).

% Optional modifier clauses, source-order: ... TOP n (more come later).
% Each modifier is preceded by whitespace; the list is empty for a
% bare SELECT-FROM.
modifier_list([M|Ms]) -->
    ws1,
    modifier(M),
    modifier_list(Ms).
modifier_list([]) --> [].

modifier(where(P)) -->
    keyword(where),
    ws1,
    predicate_or(P).
modifier(group_by(Cs)) -->
    keyword(group),
    ws1, keyword(by),
    ws1,
    group_by_list(Cs).

% GROUP BY items are full value expressions — DBISAM accepts qualified
% refs (`group by orderh.ref`), function calls, etc. Bare identifiers
% are just one shape `value//1` produces, so the existing
% `group_by([identifier(a), ...])` shape stays compatible.
group_by_list([V|Vs]) -->
    value(V),
    group_by_list_rest(Vs).
group_by_list_rest([]) --> [].
group_by_list_rest([V|Vs]) -->
    ws, [','], ws,
    value(V),
    group_by_list_rest(Vs).
modifier(order_by(Os)) -->
    keyword(order),
    ws1, keyword(by),
    ws1,
    order_item_list(Os).
% HAVING — engine-validated to require GROUP BY, and to constrain
% the expression to one of: a column in GROUP BY, an aggregate also
% in the projection, or a projected-aggregate alias. Grammar accepts
% any predicate; engine catches the semantic violations.
% See memory `dbisam-having-restrictions.md` for the full quirks list.
modifier(having(P)) -->
    keyword(having),
    ws1,
    predicate_or(P).
modifier(top(N)) -->
    keyword(top),
    ws1,
    integer_literal(integer_literal(N)).

% Comma-separated ORDER BY items. Each item is a value expression
% with an optional ASC/DESC direction (default ASC when omitted).
% AST: `[ord(Item, Dir), ...]` with Dir ∈ {asc, desc}.
order_item_list([O|Os]) -->
    order_item(O),
    order_item_rest(Os).

order_item_rest([]) --> [].
order_item_rest([O|Os]) -->
    ws, [','], ws,
    order_item(O),
    order_item_rest(Os).

order_item(ord(V, desc)) -->
    value(V),
    ws1, keyword(desc).
order_item(ord(V, asc)) -->
    value(V),
    ws1, keyword(asc).
order_item(ord(V, asc)) --> value(V).

% Comma-separated identifier list (no `*` here — only identifiers).
ident_list([C|Cs]) -->
    identifier(C),
    ident_list_rest(Cs).

ident_list_rest([]) --> [].
ident_list_rest([C|Cs]) -->
    ws, [','], ws,
    identifier(C),
    ident_list_rest(Cs).

% Predicate precedence (loosest binding to tightest, SQL-standard):
%   predicate_or   = predicate_and ( OR predicate_and )*    -- left-assoc
%   predicate_and  = predicate_atom ( AND predicate_atom )* -- left-assoc
%   predicate_atom = <eq> | <is null> | <is not null>
%
% Single-predicate WHERE clauses produce the same AST as before this
% slice (just the bare atom, no `and(...)` / `or(...)` wrapper), so
% existing meaningful entries don't need expected.term migration.

predicate_or(P)   --> predicate_and(P1), or_rest(P1, P).
or_rest(L, P)     --> ws1, keyword(or),  ws1, predicate_and(R), or_rest(or(L, R), P).
or_rest(P, P)     --> [].

predicate_and(P)  --> predicate_atom(P1), and_rest(P1, P).
and_rest(L, P)    --> ws1, keyword(and), ws1, predicate_atom(R), and_rest(and(L, R), P).
and_rest(P, P)    --> [].

% Parenthesised sub-predicates are placed AT the atom level so they
% compose correctly with the precedence chain — `(a AND b) OR c` parses
% predicate_or → predicate_and → predicate_atom(`(a AND b)` → `and(a,b)`)
% then or_rest matches the OR and returns `or(and(a,b), c)`.
predicate_atom(P) -->
    ['('], ws, predicate_or(P), ws, [')'].
% NOT prefix. Probed slice #76: DBISAM accepts both `NOT (pred)` and
% bare `NOT pred`. Standard SQL precedence is NOT > AND > OR, which
% emerges naturally by placing NOT at atom level (it binds tightest).
% Order: try NOT before is_not_null so the leading `NOT` consumes
% correctly. is_not_null consumes a value-then-is-not-null pattern,
% so it won't fire on a bare leading NOT — but explicit ordering
% keeps the intent clear.
predicate_atom(not(P)) -->
    keyword(not), ws1,
    predicate_atom(P).
% Ordering matters: try IS [NOT] NULL first (the IS keyword would
% otherwise parse as an identifier). For symbolic comparison operators,
% try the longer prefixes first (`<=`, `>=`, `<>`, `!=` before `<`,
% `>`, `=`) so the lexer doesn't half-consume them.
predicate_atom(is_not_null(L)) -->
    value(L),
    ws1, keyword(is),
    ws1, keyword(not),
    ws1, keyword(null).
predicate_atom(is_null(L)) -->
    value(L),
    ws1, keyword(is),
    ws1, keyword(null).
% IN / NOT IN. RHS is either a value list `(v1, v2, ...)` or a
% single subselect `(<SELECT ...>)`. Subselect wrapped in
% `subselect(SelectTerm)` to keep value lists (list shape) and
% subqueries (functor shape) distinguishable in the AST.
%
% DBISAM accepts subqueries in EXACTLY this position — full rules in
% `dbisam-fussy-subqueries` memory file. Grammar deliberately
% over-accepts correlation and nesting; engine catches those at
% parse time and any corpus entry that exercises them gets
% `expected-divergent` with a documented [divergence] block.
%
% Order matters in the alternatives: try subselect first because
% `keyword(select)` is a stronger discriminator than the start of a
% value expression. Bare `value_list` could start with an identifier
% spelled `select` (unlikely but possible) — but the keyword match
% requires a non-identifier char after it (handled by ws1 in the
% nested rule), so backtracking still resolves correctly.
predicate_atom(not_in(L, Rhs)) -->
    value(L),
    ws1, keyword(not),
    ws1, keyword(in),
    ws, ['('], ws,
    in_rhs(Rhs),
    ws, [')'].
predicate_atom(in(L, Rhs)) -->
    value(L),
    ws1, keyword(in),
    ws, ['('], ws,
    in_rhs(Rhs),
    ws, [')'].

in_rhs(subselect(S)) --> select_chain(S).
in_rhs(Vs) --> value_list(Vs).
% BETWEEN / NOT BETWEEN — range predicate. Order: try NOT BETWEEN
% before BETWEEN so the NOT prefix gets consumed correctly.
% Probed accepted on rivsem04: bare numeric, qualified-col, `?`
% params on both Lo and Hi, NOT BETWEEN. Lo/Hi are full value
% expressions per standard.
predicate_atom(not_between(V, Lo, Hi)) -->
    value(V),
    ws1, keyword(not),
    ws1, keyword(between),
    ws1, value(Lo),
    ws1, keyword(and),
    ws1, value(Hi).
predicate_atom(between(V, Lo, Hi)) -->
    value(V),
    ws1, keyword(between),
    ws1, value(Lo),
    ws1, keyword(and),
    ws1, value(Hi).
predicate_atom(not_like(L, R)) -->
    value(L),
    ws1, keyword(not),
    ws1, keyword(like),
    ws1, string_literal(R).
predicate_atom(like(L, R)) -->
    value(L),
    ws1, keyword(like),
    ws1, string_literal(R).
predicate_atom(cmp(Op, L, R)) -->
    value(L),
    ws, cmp_op(Op), ws,
    value(R).
predicate_atom(eq(L, R)) -->
    value(L),
    ws, ['='], ws,
    value(R).

% Comparison operators — longer prefixes first.
% `<>` and `!=` both mean "not equal"; canonicalise to `ne`.
cmp_op(le) --> ['<','='].
cmp_op(ge) --> ['>','='].
cmp_op(ne) --> ['<','>'].
cmp_op(ne) --> ['!','='].
cmp_op(lt) --> ['<'].
cmp_op(gt) --> ['>'].

% Comma-separated value list (for IN).
value_list([V|Vs]) -->
    value(V),
    value_list_rest(Vs).

value_list_rest([]) --> [].
value_list_rest([V|Vs]) -->
    ws, [','], ws,
    value(V),
    value_list_rest(Vs).

% A value expression. Standard SQL arithmetic precedence chain:
%   additive       — left-assoc `+`, `-`, `||`
%   multiplicative — left-assoc `*`, `/`, `MOD`
%   unary          — prefix `-`
%   primary        — literals, idents, function calls, parens, CAST
%
% DBISAM-specific probing on rivsem04 (2026-05-27): `%` is rejected
% (use `MOD` instead); `||` and string `+` both work for concatenation
% (engine type-checks at parse time); `&` is rejected. Unary minus
% works on both literals and column references. See probe results in
% the slice #37 notes.
value(V) --> additive(V).

additive(A) -->
    multiplicative(L),
    add_rest(L, A).
add_rest(L, A) --> ws, ['+'], ws, multiplicative(R), add_rest(arith(add, L, R), A).
add_rest(L, A) --> ws, ['-'], ws, multiplicative(R), add_rest(arith(sub, L, R), A).
add_rest(L, A) --> ws, ['|','|'], ws, multiplicative(R), add_rest(arith(concat, L, R), A).
add_rest(V, V) --> [].

multiplicative(M) -->
    unary(L),
    mul_rest(L, M).
mul_rest(L, M) --> ws, ['*'], ws, unary(R), mul_rest(arith(mul, L, R), M).
mul_rest(L, M) --> ws, ['/'], ws, unary(R), mul_rest(arith(div, L, R), M).
mul_rest(L, M) --> ws1, keyword(mod), ws1, unary(R), mul_rest(arith(mod, L, R), M).
mul_rest(V, V) --> [].

unary(neg(V)) --> ['-'], ws, unary(V).
unary(V) --> primary(V).

% Primary: a value with no infix arithmetic above it. Same paren-strip
% rule as projection items. Order matters: try the longer prefixes
% (CAST, function_call, qualified) before bare identifier so `a.b`
% doesn't get half-consumed as `identifier(a)` followed by stray
% `.b`, and `SUM(x)` doesn't get half-consumed as `identifier(SUM)`.
% The paren branch recurses back into `value//1` so a parenthesised
% subexpression resets the precedence level (`(1+2)*3` works).
primary(V) --> ['('], ws, value(V), ws, [')'].
primary(V) --> cast_expr(V).
primary(V) --> case_expr(V).
primary(V) --> function_call(V).
primary(qualified(Q, N)) -->
    identifier(Q), ['.'], identifier(N).
% Boolean literals. Probed slice #73: `TRUE` and `FALSE` are
% accepted by the engine as value literals (e.g., `WHERE col = TRUE`
% works). Order BEFORE identifier so TRUE/FALSE consume as literals,
% not as column references. Existing corpus entries that compared
% against TRUE (0109, 0113) get a richer AST after this change.
primary(boolean_literal(true))  --> keyword(true).
primary(boolean_literal(false)) --> keyword(false).
primary(V) --> identifier(V).
primary(V) --> decimal_literal(V).
primary(V) --> integer_literal(V).
primary(V) --> string_literal(V).
% JDBC-style positional parameter. DBISAM has native support — `?`
% is accepted as a value-position placeholder in WHERE, JOIN ON,
% INSERT VALUES, and similar slots. Probed slice (post-template-
% harvest): `select … where col = ?` and `insert into t values (?, ?, …)`
% both parsed by the engine. No name/index in the AST; positional
% form only (`:name` and bracketed `[?param]` rejected by engine).
primary(parameter(positional)) --> ['?'].

% CASE expression — two forms, both terminated by END.
%   Searched: CASE WHEN <pred> THEN <val> [...]* [ELSE <val>] END
%   Simple:   CASE <expr> WHEN <val> THEN <val> [...]* [ELSE <val>] END
%
% AST:
%   case_when([when(Cond, Result), ...], else(Val) | no_else)
%   case_match(Expr, [when(Val, Result), ...], else(Val) | no_else)
%
% Try the searched form first by peeking for `WHEN` immediately after
% `CASE` — that disambiguates with no real backtracking cost. The
% simple form falls out as the alternative.
%
% Probed on rivsem04: both forms accept ELSE-less variants, multiple
% WHEN clauses, nesting, use as projection or as operand of arith.
case_expr(C) -->
    keyword(case),
    ws1,
    case_body(C),
    ws1,
    keyword(end).

case_body(case_when(Whens, Else)) -->
    case_when_list_searched(Whens),
    case_else_opt(Else).
case_body(case_match(Expr, Whens, Else)) -->
    value(Expr),
    ws1,
    case_when_list_simple(Whens),
    case_else_opt(Else).

case_when_list_searched([when(C, R) | Rest]) -->
    keyword(when), ws1,
    predicate_or(C), ws1,
    keyword(then), ws1,
    value(R),
    case_when_list_searched_more(Rest).
case_when_list_searched_more([]) --> [].
case_when_list_searched_more(L) -->
    ws1, case_when_list_searched(L).

case_when_list_simple([when(V, R) | Rest]) -->
    keyword(when), ws1,
    value(V), ws1,
    keyword(then), ws1,
    value(R),
    case_when_list_simple_more(Rest).
case_when_list_simple_more([]) --> [].
case_when_list_simple_more(L) -->
    ws1, case_when_list_simple(L).

case_else_opt(else(V)) -->
    ws1, keyword(else), ws1,
    value(V).
case_else_opt(no_else) --> [].

% CAST(<expr> AS <type>) — special form. `<type>` is one of DBISAM's
% built-in type keywords with an optional parenthesised size (only
% applicable to VARCHAR / CHAR; ignored by the grammar for other types).
% Case-insensitive on CAST, AS, and the type names. AST canonicalises
% the type name to UPPERCASE so casts to `varchar(255)` and `VARCHAR(255)`
% produce the same term.
cast_expr(cast(E, T)) -->
    keyword(cast),
    ws, ['('], ws,
    value(E),
    cast_separator,
    cast_type(T),
    ws, [')'].

% DBISAM accepts both `CAST(expr AS type)` (SQL standard) and
% `CAST(expr, type)` (DBISAM extension). The separator surfaces only
% during parsing; the AST and generator emit the canonical AS-form.
cast_separator --> ws1, keyword(as), ws1.
cast_separator --> ws, [','], ws.

cast_type(type(TypeAtom, [Size])) -->
    type_keyword(TypeAtom),
    ws, ['('], ws, integer_literal(integer_literal(Size)), ws, [')'].
cast_type(type(TypeAtom, [])) -->
    type_keyword(TypeAtom).

% Function call: `<NAME>(<arg-list>)` where NAME must be in the
% verified `valid_function/1` catalogue (auto-generated from live
% engine probing — see grammar/functions.pl). Calls to unknown
% names fail to parse, matching the engine's parse-time validation.
%
% The argument list is comma-separated values, with one special
% form: `COUNT(*)` and any other valid wildcard arg list `[star]`.
% Mixed forms (`COUNT(a, *)`) are syntactically accepted; the engine
% rejects them, but matching that strictness would require knowing
% per-function arity (deferred — function_arg_shape/2 has some of
% this but enforcement is for a future slice).
%
% EXTRACT is a special form: `EXTRACT(<field> FROM <expr>)`. Field is
% a bareword keyword from a fixed set (DBISAM tells us via the engine
% error: YEAR/MONTH/WEEK/DAY/DAYOFWEEK/DAYOFYEAR/HOUR/MINUTE/SECOND/
% MSECOND). EXTRACT is tried before the general function-call rule so
% its `<field> FROM ...` shape doesn't get misparsed as a 2-arg call.
%
% AST:
%   extract(FieldAtom, Expr)             -- EXTRACT(field FROM expr)
%   trim(SideAtom, Chars, Expr)          -- TRIM(side chars FROM expr)
%   function_call(NameAtom, ArgList)     -- everything else
function_call(extract(Field, Expr)) -->
    keyword(extract),
    ws, ['('], ws,
    extract_field(Field),
    ws1, keyword(from),
    ws1, value(Expr),
    ws, [')'].
% TRIM is a special form. DBISAM requires:
%   TRIM(<side> <chars-string-literal> FROM <expr>)
%   TRIM(<side> <chars-string-literal>, <expr>)    -- comma-separator variant
% Both shapes accepted; both store the same `trim/3` AST. Generator
% emits the FROM form (SQL-standard).
function_call(trim(Side, Chars, Expr)) -->
    keyword(trim),
    ws, ['('], ws,
    trim_side(Side),
    ws1, string_literal(Chars),
    ws, trim_separator,
    ws, value(Expr),
    ws, [')'].

trim_side(leading)  --> keyword(leading).
trim_side(trailing) --> keyword(trailing).
trim_side(both)     --> keyword(both).

trim_separator --> keyword(from).
trim_separator --> [','].
% CONCAT — special form: DBISAM accepts the SQL Server-ish
% `CONCAT(a WITH b)` separator in addition to the standard
% `CONCAT(a, b)`. Strictly binary either way (3-arg CONCAT rejected
% by engine — see memory `dbisam-function-quirks`). `WITH` is
% CONCAT-specific; COALESCE/IF/etc. reject it. Try the WITH form
% first; if it fails, fall through to the generic function_call rule
% which handles the comma form.
function_call(function_call('CONCAT', [A, B])) -->
    keyword(concat),
    ws, ['('], ws,
    func_arg(A),
    ws1, keyword(with),
    ws1, func_arg(B),
    ws, [')'].
function_call(function_call(Name, Args)) -->
    identifier(identifier(NameAtom)),
    { atom_upper(NameAtom, Name), valid_function(Name) },
    ws, ['('], ws,
    func_arg_list(Args),
    ws, [')'],
    { check_function_arity(Name, Args) }.

% Arity enforcement (slice #65). Reject a function call whose arg
% count doesn't match any documented shape — unless the function is
% declared variadic, or no shapes are documented at all (in which
% case defer to the engine).
%
% `[star]` for COUNT(*) and similar wildcards is treated as length 1
% to match the documented `COUNT/1` shape.
check_function_arity(_Name, [star]) :- !.
check_function_arity(Name, _Args) :-
    function_variadic(Name), !.
check_function_arity(Name, _Args) :-
    \+ function_arg_shape(Name, _), !.
check_function_arity(Name, Args) :-
    length(Args, N),
    function_arg_shape(Name, Shape),
    length(Shape, N), !.

extract_field('YEAR')       --> keyword(year).
extract_field('MONTH')      --> keyword(month).
extract_field('WEEK')       --> keyword(week).
extract_field('DAYOFWEEK')  --> keyword(dayofweek).
extract_field('DAYOFYEAR')  --> keyword(dayofyear).
extract_field('DAY')        --> keyword(day).
extract_field('HOUR')       --> keyword(hour).
extract_field('MINUTE')     --> keyword(minute).
extract_field('SECOND')     --> keyword(second).
extract_field('MSECOND')    --> keyword(msecond).

func_arg_list([]) --> [].
func_arg_list([star]) --> ['*'].
func_arg_list([A|As]) -->
    func_arg(A),
    func_arg_list_rest(As).

% A function argument is either a value expression or a predicate
% (chained AND/OR over comparisons, IS NULL, LIKE, IN, etc.).
% DBISAM's `IF(cond, then, else)` and `IFNULL(cond, …)` accept
% comparisons and Boolean compounds as their first arg — that's why
% predicates show up here, alongside plain values. Other functions
% (ABS, COALESCE, ...) only accept value-typed args, but the engine
% catches type mismatches at parse time — the grammar stays
% schema-and-type-agnostic. Try predicate_or first so `1=1` resolves
% to `cmp(eq, 1, 1)`; bare values fall through to the second clause.
func_arg(P) --> predicate_or(P).
func_arg(V) --> value(V).

func_arg_list_rest([]) --> [].
func_arg_list_rest([A|As]) -->
    ws, [','], ws,
    value(A),
    func_arg_list_rest(As).

% Emit an identifier atom, double-quoting if the atom isn't a valid
% bare identifier (contains spaces, starts with a digit, contains
% punctuation, etc.). Canonical form: bare when possible, quoted
% otherwise. Round-trip stable — re-parsing the quoted form produces
% the same atom.
gen_ident_atom(A, Chars) :-
    atom_chars(A, AC),
    ( bare_ident_chars_ok(AC)
    -> Chars = AC
    ;  append([['"'], AC, ['"']], Chars)
    ).

bare_ident_chars_ok([]) :- false.
bare_ident_chars_ok([C|Cs]) :-
    ident_start(C),
    all_ident_cont(Cs).

all_ident_cont([]).
all_ident_cont([C|Cs]) :- ident_cont(C), all_ident_cont(Cs).

% Atom uppercase helper. Mirrors atom_lower/2 elsewhere in this file.
atom_upper(A, U) :-
    atom_chars(A, Cs),
    maplist(to_upper, Cs, UCs),
    atom_chars(U, UCs).

to_upper(C, U) :-
    ( C @>= 'a', C @=< 'z'
    -> char_code(C, L), Uc is L - 32, char_code(U, Uc)
    ; U = C
    ).

% DBISAM type keywords as listed in CORPUS-side notes / Elevate docs.
% Match case-insensitively; the AST stores the canonical UPPERCASE atom.
type_keyword('VARCHAR')  --> keyword(varchar).
type_keyword('CHAR')     --> keyword(char).
type_keyword('INTEGER')  --> keyword(integer).
type_keyword('SMALLINT') --> keyword(smallint).
type_keyword('LARGEINT') --> keyword(largeint).
type_keyword('FLOAT')    --> keyword(float).
type_keyword('BOOLEAN')  --> keyword(boolean).
type_keyword('DATE')     --> keyword(date).
type_keyword('TIME')     --> keyword(time).
type_keyword('DATETIME') --> keyword(datetime).
type_keyword('BLOB')     --> keyword(blob).
type_keyword('MEMO')     --> keyword(memo).

column_list([C|Cs]) -->
    column_or_star(C),
    column_list_rest(Cs).

column_list_rest([]) --> [].
column_list_rest([C|Cs]) -->
    ws, [','], ws,
    column_or_star(C),
    column_list_rest(Cs).

% A single projection item — a bare item optionally followed by an
% alias (`AS <name>` or just `<name>`). AST elements:
%   star                                       -- the wildcard
%   qualified(identifier(Q), identifier(N))    -- table.column
%   cast(Expr, type(TypeAtom, Args))           -- CAST(e AS T) etc.
%   function_call(NameAtom, Args)              -- SUM(col), COUNT(*), …
%   extract(Field, Expr)                       -- EXTRACT(field FROM e)
%   trim(Side, Chars, Expr)                    -- TRIM(side chars FROM e)
%   identifier(Atom)                           -- bare column name
%   aliased(Item, identifier(AliasAtom))       -- any of the above + alias
column_or_star(C) -->
    column_or_star_bare(C0),
    column_alias_opt(C0, C).

% Optional column alias. Try AS-form first (explicit), then bare-form
% with keyword guard, then no alias.
column_alias_opt(Bare, aliased(Bare, A)) -->
    ws1, keyword(as),
    ws1, identifier(A).
column_alias_opt(Bare, aliased(Bare, identifier(AA))) -->
    ws1, identifier(identifier(AA)),
    { atom_lower(AA, L), \+ is_projection_terminator(L) }.
column_alias_opt(Bare, Bare) --> [].

% Words that, if seen after a projection item, are NOT aliases but
% start the next clause (FROM) or are special keywords (AS handled
% explicitly above).
is_projection_terminator(from).
is_projection_terminator(as).

% A bare projection item (no alias). `*` is special — anything else
% is an arbitrary value expression, which gives the projection full
% access to the arithmetic precedence chain defined in `value//1`.
column_or_star_bare(star) --> ['*'].
column_or_star_bare(C) --> value(C).


% ============================================================
% Lexical
% ============================================================

% Whitespace — zero or more chars, treating SQL comments as
% whitespace-equivalent. Probed slice #66: DBISAM accepts both
% `--` line comments (to end-of-line) and `/* */` block comments
% (non-nesting). Block-comment nesting is rejected — `/* a /* b */ c */`
% closes at the first `*/` and the engine then chokes on the
% trailing `c */`. The grammar matches this behaviour.
%
% Cuts after a successful token-consume prevent the arithmetic `-`
% rule from undoing a `--` comment match: once we've recognised the
% double-dash as a comment, the parser commits and won't backtrack
% to split the `--` into two unary-minus tokens.
ws --> line_comment, !, ws.
ws --> block_comment, !, ws.
ws --> [C], { ws_char(C) }, ws.
ws --> [].

% Whitespace — one or more. Same alternatives as ws but at least
% one match is required.
ws1 --> line_comment, !, ws.
ws1 --> block_comment, !, ws.
ws1 --> [C], { ws_char(C) }, ws.

ws_char(' ').
ws_char('\t').
ws_char('\n').
ws_char('\r').

% `--` to end-of-line (or end-of-input). Engine probed (slice #66):
% line comment terminates at any line-ending character; entire
% comment is treated as whitespace.
line_comment --> ['-', '-'], line_comment_tail.

line_comment_tail --> ['\n'].
line_comment_tail --> ['\r'].
line_comment_tail --> [_], line_comment_tail.
line_comment_tail --> [].                            % EOF (no newline)

% `/* */` block comment, NOT nesting. Engine probed: nested forms
% close at the first `*/` and trail garbage afterwards. The grammar
% matches that by being non-nesting too.
block_comment --> ['/', '*'], block_comment_tail.

block_comment_tail --> ['*', '/'].
block_comment_tail --> [_], block_comment_tail.

% Identifier — either bare (letter/underscore + alnum/underscore) or
% double-quoted (any chars except embedded `"`). Both produce the
% same `identifier(Atom)` AST term; the atom carries the contained
% text verbatim. DBISAM accepts the quoted form anywhere a bare one
% goes — column refs, table refs, aliases, qualified-ident parts.
identifier(identifier(Atom)) -->
    ['"'],
    quoted_ident_chars(Cs),
    ['"'],
    { Cs \= [], atom_chars(Atom, Cs) }.
% Square-bracket form. Probed on rivsem04 (slice #40): DBISAM accepts
% `[code]`, `[CUSTOMER]`, `CUSTOMER.[code]`, `as [alias]`, etc., but
% rejects bracketed forms whose contents aren't a valid bare identifier
% (`[some col]`, `[123]`, `[order#]` all reject). So this is a
% delimiter variant — same char class as bare — not a SQL-Server-style
% quoted identifier that admits arbitrary chars.
identifier(identifier(Atom)) -->
    ['['],
    [C], { ident_start(C) },
    ident_rest(Cs),
    [']'],
    { atom_chars(Atom, [C|Cs]) }.
identifier(identifier(Atom)) -->
    [C], { ident_start(C) },
    ident_rest(Cs),
    { atom_chars(Atom, [C|Cs]) }.

quoted_ident_chars([C|Cs]) --> [C], { C \== '"' }, quoted_ident_chars(Cs).
quoted_ident_chars([]) --> [].

ident_start(C) :- alpha_char(C).
ident_start('_').

ident_rest([C|Cs]) --> [C], { ident_cont(C) }, ident_rest(Cs).
ident_rest([]) --> [].

ident_cont(C) :- alpha_char(C).
ident_cont(C) :- digit_char(C).
ident_cont('_').

alpha_char(C) :- C @>= 'a', C @=< 'z'.
alpha_char(C) :- C @>= 'A', C @=< 'Z'.
digit_char(C) :- C @>= '0', C @=< '9'.

% Integer literal — not used by the seed corpus's SELECT path yet,
% but defined now because the next likely slice (WHERE with numeric
% predicates) needs it. Exposed via `integer_literal//1`.
integer_literal(integer_literal(N)) -->
    [D], { digit_char(D) },
    digits(Ds),
    { number_chars(N, [D|Ds]) }.

digits([D|Ds]) --> [D], { digit_char(D) }, digits(Ds).
digits([]) --> [].

% Decimal / float literal. Probed slice #61: DBISAM accepts every
% common shape — `3.14`, `0.5`, `.5`, `5.`, `1.5e3`, `1.5E-3`, `1e3`.
% Stored as `decimal_literal(Atom)` with the textual representation
% in the atom to preserve exactness on round-trip (avoids any
% binary-float rounding). Must be tried BEFORE `integer_literal` in
% primary//1 so `1.5` doesn't get truncated to integer `1`.
%
% Shapes admitted:
%   <digits>.<digits>[exp]    — `3.14`, `3.14e5`
%   <digits>.[exp]            — `5.`, `5.e3`
%   .<digits>[exp]            — `.5`, `.5e3`
%   <digits><exp>             — `1e3`, `1E-5`
% where <exp> is `[eE] [+-]? <digits>`.
decimal_literal(decimal_literal(Atom)) -->
    dec_with_dot(Cs),
    { atom_chars(Atom, Cs) }.
decimal_literal(decimal_literal(Atom)) -->
    digits1(Is),
    exp_part(Es),
    { append(Is, Es, Cs), atom_chars(Atom, Cs) }.

dec_with_dot(Cs) -->
    digits(Is),
    ['.'],
    digits(Fs),
    exp_opt(Es),
    { ( Is \= [] ; Fs \= [] ),
      append([Is, ['.'], Fs, Es], Cs) }.

digits1([D|Ds]) --> [D], { digit_char(D) }, digits(Ds).

exp_opt(Es) --> exp_part(Es).
exp_opt([])  --> [].

exp_part([E|Rest]) -->
    [E], { e_char(E) },
    sign_opt(Sign),
    digits1(Ds),
    { append(Sign, Ds, Rest) }.

sign_opt(['+']) --> ['+'].
sign_opt(['-']) --> ['-'].
sign_opt([])    --> [].

e_char('e').
e_char('E').

% Single-quoted string literal with standard-SQL doubled-quote
% escape. Probed slice #60: DBISAM accepts `'O''Brien'` and
% interprets it as the 7-char string `O'Brien` (per SQL standard).
% Backslash sequences (`\n`, `\'`) are NOT interpreted — backslash
% is just a literal character inside a string. The grammar therefore
% only needs to handle the doubled-quote escape; other characters
% (including `\`) pass through verbatim.
%
% Order in `string_chars` matters: try the doubled-quote `''` clause
% FIRST so a `'` followed by another `'` doesn't terminate the
% string prematurely. The atom built into the AST holds the decoded
% content (one `'` per source-level `''`).
string_literal(string_literal(Atom)) -->
    [''''],
    string_chars(Cs),
    [''''],
    { atom_chars(Atom, Cs) }.

string_chars([''''|Cs]) --> ['''', ''''], string_chars(Cs).
string_chars([C|Cs])    --> [C], { C \== '''' }, string_chars(Cs).
string_chars([]) --> [].

% Keyword — case-insensitive match against an atom argument.
keyword(K) -->
    { atom_chars(K, KChars) },
    keyword_chars(KChars).

keyword_chars([]) --> [].
keyword_chars([K|Ks]) -->
    [C], { char_eq_ci(C, K) },
    keyword_chars(Ks).

char_eq_ci(A, B) :- to_lower(A, L), to_lower(B, L).

to_lower(C, L) :-
    ( C @>= 'A', C @=< 'Z'
    -> char_code(C, U), Lc is U + 32, char_code(L, Lc)
    ; L = C
    ).
