:- module(functions, [valid_function/1]).

% DBISAM SQL functions verified to exist on the live engine.
% Auto-generated by tools/probe-functions.sh — do not hand-edit.
% Each `valid_function/1` fact is a function the engine recognises;
% the grammar's function-call rule must reject anything else, since
% the engine does so at parse time.

valid_function('ABS').
valid_function('ACOS').
valid_function('ASIN').
valid_function('ATAN').
valid_function('ATAN2').
valid_function('AVG').
valid_function('CEIL').
valid_function('CEILING').
valid_function('COALESCE').
valid_function('CONCAT').
valid_function('COS').
valid_function('COT').
valid_function('COUNT').
valid_function('DAYSFROMMSECS').
valid_function('DEGREES').
valid_function('EXP').
valid_function('FLOOR').
valid_function('HOURSFROMMSECS').
valid_function('IDENT_CURRENT').
valid_function('IF').
valid_function('IFNULL').
valid_function('LASTAUTOINC').
valid_function('LCASE').
valid_function('LEFT').
valid_function('LENGTH').
valid_function('LIST').
valid_function('LOG').
valid_function('LOG10').
valid_function('LOWER').
valid_function('LTRIM').
valid_function('MAX').
valid_function('MIN').
valid_function('MINSFROMMSECS').
valid_function('MOD').
valid_function('MSECSFROMMSECS').
valid_function('NULLIF').
valid_function('OCCURS').
valid_function('PI').
valid_function('POS').
valid_function('POSITION').
valid_function('POWER').
valid_function('RADIANS').
valid_function('RAND').
valid_function('REPEAT').
valid_function('REPLACE').
valid_function('RIGHT').
valid_function('ROUND').
valid_function('RTRIM').
valid_function('RUNSUM').
valid_function('SECSFROMMSECS').
valid_function('SIGN').
valid_function('SIN').
valid_function('SQRT').
valid_function('STDDEV').
valid_function('SUBSTRING').
valid_function('SUM').
valid_function('TAN').
valid_function('TEXTOCCURS').
valid_function('TEXTSEARCH').
valid_function('TRUNC').
valid_function('TRUNCATE').
valid_function('UCASE').
valid_function('UPPER').
valid_function('YEARSFROMMSECS').

% Manually added — these were missed from the docs-extraction candidate
% list but verified to exist on the engine via direct probe.
valid_function('CURRENT_DATE').
valid_function('CURRENT_TIME').
valid_function('CURRENT_TIMESTAMP').
