:- module(function_sigs, [function_arg_shape/2, function_variadic/1]).

% Accepted literal-argument shapes per function, as confirmed by live
% engine probing. Auto-generated by tools/probe-functions.sh.
%
% function_arg_shape(Name, ArgTypes) — ArgTypes is a list of arg-type
% atoms in {numeric, string} (only literal shapes were probed). A
% function with multiple accepted shapes has multiple facts.
%
% Functions with `exists` but no `accepted` shape (so the engine
% recognises the name but none of our literal probes were valid for it
% — typically aggregates that need column refs, or 0-arg functions our
% probe missed) get no fact here; the grammar's function-call rule
% should accept any arg shape for such functions until corpus entries
% force a tighter check.

% function_variadic(Name) — declared for functions that accept any
% arg count above 1 (probed: COALESCE accepted 20 args). The grammar's
% arity check (slice #65) skips length-matching for variadic
% functions; documented arg shapes still apply to type-hinted
% callers.
function_variadic('COALESCE').

function_arg_shape('ABS', [numeric]).
function_arg_shape('ACOS', [numeric]).
function_arg_shape('ASIN', [numeric]).
function_arg_shape('ATAN', [numeric]).
function_arg_shape('ATAN2', [numeric, numeric]).
function_arg_shape('AVG', [numeric]).
function_arg_shape('CEIL', [numeric]).
function_arg_shape('CEILING', [numeric]).
function_arg_shape('COALESCE', [numeric]).
function_arg_shape('COALESCE', [string]).
function_arg_shape('COALESCE', [numeric, numeric]).
function_arg_shape('COALESCE', [string, string]).
function_arg_shape('COALESCE', [numeric, numeric, numeric]).
function_arg_shape('CONCAT', [string, string]).
function_arg_shape('COS', [numeric]).
function_arg_shape('COT', [numeric]).
function_arg_shape('COUNT', [numeric]).
function_arg_shape('COUNT', [string]).
function_arg_shape('DAYSFROMMSECS', [numeric]).
function_arg_shape('DEGREES', [numeric]).
function_arg_shape('EXP', [numeric]).
function_arg_shape('FLOOR', [numeric]).
function_arg_shape('HOURSFROMMSECS', [numeric]).
function_arg_shape('IF', [numeric, numeric, numeric]).
function_arg_shape('IFNULL', [numeric, numeric, numeric]).
function_arg_shape('LCASE', [string]).
function_arg_shape('LEFT', [string, numeric]).
function_arg_shape('LENGTH', [string]).
function_arg_shape('LIST', [string]).
function_arg_shape('LIST', [string, string]).
function_arg_shape('LOG', [numeric]).
function_arg_shape('LOG10', [numeric]).
function_arg_shape('LOWER', [string]).
function_arg_shape('LTRIM', [string]).
function_arg_shape('MAX', [numeric]).
function_arg_shape('MAX', [string]).
function_arg_shape('MIN', [numeric]).
function_arg_shape('MIN', [string]).
function_arg_shape('MINSFROMMSECS', [numeric]).
function_arg_shape('MOD', [numeric, numeric]).
function_arg_shape('MSECSFROMMSECS', [numeric]).
function_arg_shape('NULLIF', [numeric, numeric]).
function_arg_shape('NULLIF', [string, string]).
function_arg_shape('OCCURS', [string, string]).
function_arg_shape('PI', []).
function_arg_shape('POS', [string, string]).
function_arg_shape('POSITION', [string, string]).
function_arg_shape('POWER', [numeric, numeric]).
function_arg_shape('RADIANS', [numeric]).
function_arg_shape('RAND', []).
function_arg_shape('RAND', [numeric]).
function_arg_shape('REPEAT', [string, numeric]).
function_arg_shape('RIGHT', [string, numeric]).
function_arg_shape('ROUND', [numeric]).
function_arg_shape('ROUND', [numeric, numeric]).
function_arg_shape('RTRIM', [string]).
function_arg_shape('RUNSUM', [numeric]).
function_arg_shape('SECSFROMMSECS', [numeric]).
function_arg_shape('SIGN', [numeric]).
function_arg_shape('SIN', [numeric]).
function_arg_shape('SQRT', [numeric]).
function_arg_shape('STDDEV', [numeric]).
function_arg_shape('SUBSTRING', [string, numeric]).
function_arg_shape('SUM', [numeric]).
function_arg_shape('TAN', [numeric]).
function_arg_shape('TRUNC', [numeric]).
function_arg_shape('TRUNC', [numeric, numeric]).
function_arg_shape('TRUNCATE', [numeric]).
function_arg_shape('TRUNCATE', [numeric, numeric]).
function_arg_shape('UCASE', [string]).
function_arg_shape('UPPER', [string]).
function_arg_shape('YEARSFROMMSECS', [numeric]).

function_arg_shape('CURRENT_DATE', []).
function_arg_shape('CURRENT_TIME', []).
function_arg_shape('CURRENT_TIMESTAMP', []).

% Manually added arity shapes — verified by live probing during
% slice #65 catalogue audit. These weren't picked up by the original
% probe-functions.sh run because the probe tool only tries a small
% fixed set of literal-arg shapes.
function_arg_shape('SUBSTRING', [string, numeric, numeric]).
function_arg_shape('REPLACE', [string, string, string]).
function_arg_shape('TEXTSEARCH', [string, string]).
function_arg_shape('TEXTOCCURS', [string, string]).

% Slice #77 — niche-function arities verified via mrsflow.
% LASTAUTOINC and IDENT_CURRENT both take a single table-name
% string arg (bare and nullary forms rejected).
function_arg_shape('LASTAUTOINC', [string]).
function_arg_shape('IDENT_CURRENT', [string]).
